# Generated by Django 2.2.9 on 2020-02-04 21:54

from django.db import migrations, models
import django.db.models.deletion
import mex.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.CharField(max_length=52, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('height', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('hash', mex.fields.HashField(max_length=32, unique=True)),
                ('merkleroot', mex.fields.HashField(max_length=32)),
                ('time', models.DateTimeField()),
                ('txcount', models.PositiveSmallIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('miner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mex.Address')),
            ],
            options={
                'get_latest_by': 'height',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('name', models.CharField(max_length=52, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', mex.fields.HashField(max_length=32, unique=True)),
                ('idx', models.PositiveSmallIntegerField(null=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mex.Block')),
            ],
            options={
                'ordering': ('-block', 'idx'),
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_idx', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=28, null=True)),
                ('spent', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs_for_addr', to='mex.Address')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs_for_tx', to='mex.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinbase', models.BooleanField()),
                ('spends', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputs_for_output', to='mex.Output')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs_for_tx', to='mex.Transaction')),
            ],
        ),
    ]
