# Generated by Django 2.2.9 on 2020-02-04 22:16

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import mex.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.CharField(max_length=52, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('height', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('hash', mex.fields.SHA256Field(max_length=64, unique=True)),
                ('merkleroot', mex.fields.SHA256Field(max_length=64)),
                ('time', models.DateTimeField()),
                ('txcount', models.PositiveSmallIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('miner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mex.Address')),
            ],
            options={
                'get_latest_by': 'height',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('hash', mex.fields.SHA256Field(max_length=64, primary_key=True, serialize=False)),
                ('idx', models.PositiveSmallIntegerField(null=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mex.Block')),
            ],
            options={
                'ordering': ('-block', 'idx'),
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('confirmed', models.IntegerField(editable=False)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('indexes', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('items', models.IntegerField(editable=False)),
                ('keys', models.IntegerField(editable=False)),
                ('name', models.CharField(editable=False, max_length=52, primary_key=True, serialize=False)),
                ('publishers', models.IntegerField(editable=False)),
                ('restrict', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('retrieve', models.NullBooleanField(editable=False)),
                ('salted', models.NullBooleanField(editable=False)),
                ('streamref', models.CharField(editable=False, max_length=255)),
                ('subscribed', models.BooleanField(editable=False)),
                ('synchronized', models.BooleanField(editable=False)),
                ('monitor', models.BooleanField(default=False, help_text='Import stream items to mex database.')),
                ('show', models.BooleanField(default=True, help_text='Show steam in frontend.')),
                ('custom_description', models.CharField(blank=True, default='', help_text='Custom stream description for frontend.', max_length=256)),
                ('createtxid', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='mex.Transaction')),
                ('creators', models.ManyToManyField(editable=False, to='mex.Address')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_idx', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=28, null=True)),
                ('spent', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs_for_addr', to='mex.Address')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs_for_tx', to='mex.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinbase', models.BooleanField()),
                ('spends', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputs_for_output', to='mex.Output')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs_for_tx', to='mex.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='StreamItem',
            fields=[
                ('output', models.OneToOneField(editable=False, help_text='The transaction output that created this stream item.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mex.Output')),
                ('available', models.BooleanField(editable=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), editable=False, size=None)),
                ('offchain', models.BooleanField(editable=False)),
                ('time', models.DateTimeField(editable=False)),
                ('valid', models.BooleanField(editable=False)),
                ('publishers', models.ManyToManyField(editable=False, to='mex.Address')),
                ('stream', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mex.Stream')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.AddIndex(
            model_name='streamitem',
            index=models.Index(fields=['-time'], name='mex_streami_time_aa3b52_idx'),
        ),
    ]
