# Generated by Django 2.2.12 on 2020-05-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamitem',
            name='output',
        ),
        migrations.RemoveField(
            model_name='streamitem',
            name='publishers',
        ),
        migrations.RemoveField(
            model_name='streamitem',
            name='stream',
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
        migrations.DeleteModel(
            name='StreamItem',
        ),
    ]
